### ISSUE TITLE
Remove score dependency 

### ISSUE THREAD

**Issue by victorjourne** [arbezlo/PAWS_custom_dataloaders#6]
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/paws/main.py", line 86, in process_main
    return paws(params, run)
  File "/workspace/paws/src/paws_train.py", line 204, in main
    supervised_sampler) = init_data(
  File "/workspace/paws/src/data_manager_clustervec.py", line 142, in init_data
    return _init_clustervec_data(
  File "/workspace/paws/src/data_manager_clustervec.py", line 526, in _init_clustervec_data
    clustervec = ClusterVec(
  File "/workspace/paws/src/data_manager_clustervec.py", line 1596, in __init__
    dataframe = pd.read_csv(df_dir,usecols=['img_path',  'x1', 'y1', 'x2', 'y2', 'score' ,'target'], index_col=False)
  File "/opt/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 917, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['score']

`

**Comment by arbezlo** [comment]
Issue addressed in latest comit
